export default {
  login: "calvin-puram",
  id: 60294324,
  node_id: "MDQ6VXNlcjYwMjk0MzI0",
  avatar_url: "https://avatars2.githubusercontent.com/u/60294324?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/calvin-puram",
  html_url: "https://github.com/calvin-puram",
  followers_url: "https://api.github.com/users/calvin-puram/followers",
  following_url:
    "https://api.github.com/users/calvin-puram/following{/other_user}",
  gists_url: "https://api.github.com/users/calvin-puram/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/calvin-puram/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/calvin-puram/subscriptions",
  organizations_url: "https://api.github.com/users/calvin-puram/orgs",
  repos_url: "https://api.github.com/users/calvin-puram/repos",
  events_url: "https://api.github.com/users/calvin-puram/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/calvin-puram/received_events",
  type: "User",
  site_admin: false,
  name: "Calvin Job Puram",
  company: null,
  blog: "https://dev.to/cpuram1",
  location: "Nigeria",
  email: null,
  hireable: null,
  bio:
    "I thrive to design and develop ideas into project that makes life easy, solve problems and implement innovations.",
  twitter_username: "cpuram1",
  public_repos: 42,
  public_gists: 3,
  followers: 10,
  following: 15,
  created_at: "2020-01-25T15:20:15Z",
  updated_at: "2020-07-20T10:28:13Z",
};
